import os
import json
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

_client = None


def get_client():
    """Lazily create the Groq client so import doesn't fail without a key set."""
    global _client
    if _client is None:
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            raise RuntimeError("GROQ_API_KEY not set. Check your .env file.")
        _client = Groq(api_key=api_key)
    return _client


def llm_signal(text: str) -> dict:
    """
    Signal 1: Groq LLM classification.

    Measures holistic semantic/stylistic coherence -- whether the text
    "reads as" AI-generated (over-hedging, generic transitions, unnaturally
    even tone), per planning.md.

    Returns: {"score": float 0.0-1.0, "reasoning": str}
    score = likelihood the text is AI-generated.
    """
    client = get_client()

    prompt = f"""You are an expert at detecting AI-generated text. Analyze the following text and assess the likelihood it was generated by an AI language model versus written by a human.

Consider: sentence uniformity, hedging language, generic transitions, unnaturally even tone, overly balanced argument structure, and vocabulary patterns typical of AI writing.

Respond with ONLY valid JSON in this exact format, nothing else, no markdown fences:
{{"ai_likelihood": <float between 0.0 and 1.0>, "reasoning": "<one sentence explanation>"}}

Text to analyze:
\"\"\"{text}\"\"\"
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
        max_tokens=200,
    )

    raw = response.choices[0].message.content.strip()

    # Defensive: strip markdown code fences if the model adds them anyway
    if raw.startswith("```"):
        raw = raw.strip("`")
        if raw.lower().startswith("json"):
            raw = raw[4:]
        raw = raw.strip()

    try:
        parsed = json.loads(raw)
        score = float(parsed.get("ai_likelihood", 0.5))
        score = max(0.0, min(1.0, score))  # clamp to [0, 1]
        reasoning = parsed.get("reasoning", "")
    except (json.JSONDecodeError, ValueError, TypeError):
        # Fallback if the model doesn't return clean JSON -- don't crash the request
        score = 0.5
        reasoning = f"Could not parse model output cleanly: {raw[:100]}"

    return {"score": score, "reasoning": reasoning}


if __name__ == "__main__":
    # Quick manual test -- run `python signals.py` directly to sanity check
    # the function before wiring it into Flask.
    test_texts = [
        "Artificial intelligence represents a transformative paradigm shift in "
        "modern society. It is important to note that while the benefits of AI "
        "are numerous, it is equally essential to consider the ethical implications.",
        "ok so i finally tried that new ramen place downtown and honestly? "
        "underwhelming. the broth was fine but they put WAY too much sodium in it.",
    ]
    for t in test_texts:
        result = llm_signal(t)
        print(f"score={result['score']:.2f}  reasoning={result['reasoning']}")